version: '3.8'

services:
  web:
    build: .
    command: venv/bin/gunicorn -b :5000 --access-logfile - --error-logfile - manage:app
    depends_on:
      - db
    ports:
      - 8000:5000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=phenodoop
      - POSTGRES_PASSWORD=sr-hadoop
      - POSTGRES_DB=biowl
volumes:
  postgres_data:
    