version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b :5000 --access-logfile - --error-logfile - manage:app
    volumes:
            - .:.
    ports:
      - 8000:5000
    env_file:
      - ./.env.dev
