"""empty message

Revision ID: 238d4a9e2f14
Revises: 581640caf7bc
Create Date: 2023-02-02 14:27:50.266991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238d4a9e2f14'
down_revision = '581640caf7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runnables', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('duration')

    with op.batch_alter_table('runnables', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))

    # ### end Alembic commands ###
