import os
from os import path

thispath = path.dirname(__file__)
from .bin import dotplot

def run_dotplot(context, *args, **kwargs):
    arguments = context.parse_args('DotPlot', 'CoGe', *args, **kwargs)
    out = path.join(context.createoutdir(), path.basename(arguments["dag_file"]))
    output = dotplot.run(arguments["dag_file"], arguments["xhead"], arguments["yhead"], out)
    if not path.exists(output):
        raise ValueError("No output file is generated by DotPlot.")
    return output